#ifndef SRC_INCLUDE_SE_CUSTOM_ATTR_H_
#define SRC_INCLUDE_SE_CUSTOM_ATTR_H_

#if ZCL_METERING_SUPPORT

#define ZCL_ATTRID_CUSTOM_DEVICE_MANUFACTURER   0xF000
#define ZCL_ATTRID_CUSTOM_DEVICE_ADDRESS        0xF001
#define ZCL_ATTRID_CUSTOM_MEASUREMENT_PERIOD    0xF002

#endif /* ZCL_METERING_SUPPORT */

#endif /* SRC_INCLUDE_SE_CUSTOM_ATTR_H_ */
